DROP TABLE IF EXISTS cart_item;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS review;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS supplier_rep;
DROP TABLE IF EXISTS supplier;
